# Configuração do banco (Render)
spring.datasource.url=jdbc:postgresql://HOST:PORT/DATABASE?sslmode=require
spring.datasource.username=coin_user
spring.datasource.password=SUA_SENHA_AQUI

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true