spring.application.name=transacao-service

server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://aws-1-sa-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.flecjjdbxjmpytnkbfal
spring.datasource.password=SENHA

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.rabbitmq.host=jackal.rmq.cloudamqp.com
spring.rabbitmq.port=5672
spring.rabbitmq.username=iwwbxnxu
spring.rabbitmq.password=SENHA
spring.rabbitmq.virtual-host=iwwbxnxu

brevo.api.key=${BREVO_API_KEY:SUA_CHAVE_BREVO}
brevo.from.name=${BREVO_FROM_NAME:Coin4Students}
brevo.from.email=${BREVO_FROM_EMAIL:coin4students@gmail.com}

aluno.service.url=https://aluno-service-orux.onrender.com
